controllers/DefaultController.php
<?php
namespace ler4ik\food\controllers;

use ler4ik\food\models\DishSearch;
use ler4ik\food\models\Ingredient;
use yii\web\Controller;
use yii\db\Query;
use Yii;


class DefaultController extends Controller
{
    public function actionIndex()
    {
        $searchModel = new DishSearch();
        $searchModel->minSearchCount = $this->module->minSearchIngredient;
        $dataProvider = $searchModel->frontendSearch(Yii::$app->request->post());
        return $this->render('index',  [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * возвращает список активных ингредиентов
     * @param string $q запрос
     * @param integer $id
     * @return array
     */
    public function actionIngredientList($q = null, $id = null) {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = new Query;
            $query->select('id, name AS text')
                ->from(Ingredient::tableName())
                ->where(['like', 'name', $q])
                ->andWhere(['active' => 1])
                ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        }
        elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Ingredient::findOne($id)->name];
        }
        return $out;
    }
}

views/default/_list_item.php
<?php
use yii\helpers\Html;
?>
<h2><?= Html::encode($model->name) ?></h2>

views/default/_search_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;
use ler4ik\food\models\Ingredient;
?>

<?php
$form = ActiveForm::begin() ?>
<?php echo $form->errorSummary([$model])?>
<div class="row">
<?php for ($i=0; $i<$this->context->module->maxSearchIngredient; $i++):?>
<?php $value = ArrayHelper::getValue($model->ingredientIds, $i, null);?>
        <div class="form-group col-md-2">
            <?=Select2::widget([
                'options' => ['placeholder' => 'Search for a ingredient ...', 'class' => 'col-md'],
                'name' => 'DishSearch[ingredientIds][]',
                'initValueText' => Ingredient::findOne($value) ? Ingredient::findOne($value)->name : '',
                'value' => $value,
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 3,
                    'multiple' => false,
                    'class' => '100px',
                    'ajax' => [
                        'url' => Url::to(['default/ingredient-list']),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }')
                    ],
                ],
            ]);?>
        </div>
<?php endfor;?>
<div class="form-group">
    <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
</div>
<?php ActiveForm::end() ?>

views/default/index.php
<?php
use yii\widgets\ListView;
use ler4ik\food\models\DishSearch;
use yii\data\ActiveDataProvider;
use app\modules\food\models\Dish;
$this->title = 'Dish';
?>
<?= $this->render('_search_form', ['model' => $searchModel]);?>
<?php
echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_list_item',
]);